import { Group, SettlementTransaction, MemberBalance } from '../types';
import { formatCurrency } from './currency';
import { Language } from './i18n';

/**
 * Generates formatted text summary ready to be copied into chat apps.
 */
export function generateGroupSummaryText(
  group: Group,
  balances: MemberBalance[],
  settlements: SettlementTransaction[],
  lang: Language = 'en'
): string {
  const isVi = lang === 'vi';
  const totalAmount = group.expenses.reduce((sum, e) => sum + e.amount, 0);
  const avg = group.members.length > 0 ? totalAmount / group.members.length : 0;

  const lines: string[] = [];
  if (isVi) {
    lines.push(`📊 TỔNG KẾT CHI TIÊU: ${group.name.toUpperCase()}`);
    lines.push(`─────────────────────────────────────────`);
    lines.push(`💰 Tổng chi tiêu: ${formatCurrency(totalAmount, group.currency)}`);
    lines.push(`👥 Số thành viên: ${group.members.length} người (TB: ${formatCurrency(avg, group.currency)}/người)`);
    lines.push(`🧾 Tổng số khoản chi: ${group.expenses.length}`);
    lines.push(``);
    lines.push(`📋 SỐ DƯ TỪNG THÀNH VIÊN:`);
    balances.forEach((b) => {
      const net = b.netBalance;
      const status = net > 0 ? '🟢 ĐƯỢC NHẬN' : net < 0 ? '🔴 CẦN TRẢ' : '⚪ HOÀN TẤT';
      lines.push(
        `• ${b.memberName}: Đã chi ${formatCurrency(b.totalPaid, group.currency)} | Tiêu thụ ${formatCurrency(b.totalShare, group.currency)} ➔ ${status}: ${formatCurrency(Math.abs(net), group.currency)}`
      );
    });
    lines.push(``);
    lines.push(`⚡ LỘ TRÌNH THANH TOÁN TỐI ƯU (MỖI NGƯỜI CHỈ CHUYỂN TỐI ĐA 1 LẦN):`);
    if (settlements.length === 0) {
      lines.push(`🎉 Tất cả thành viên đã huề vốn!`);
    } else {
      settlements.forEach((tx, idx) => {
        const fromMem = group.members.find((m) => m.id === tx.fromMemberId);
        const toMem = group.members.find((m) => m.id === tx.toMemberId);
        const status = tx.isPaid ? ' [ĐÃ CHUYỂN ✅]' : ' [CHỜ CHUYỂN]';
        const paymentInfo = toMem?.paymentDetails ? ` (${toMem.paymentDetails})` : '';
        lines.push(
          `${idx + 1}. ${fromMem?.name} ➔ ${toMem?.name}: ${formatCurrency(tx.amount, group.currency)}${paymentInfo}${status}`
        );
      });
    }
    lines.push(`─────────────────────────────────────────`);
    lines.push(`Tạo bởi SplitWisePro 🚀`);
  } else {
    lines.push(`📊 EXPENSE SUMMARY: ${group.name.toUpperCase()}`);
    lines.push(`─────────────────────────────────────────`);
    lines.push(`💰 Total Spent: ${formatCurrency(totalAmount, group.currency)}`);
    lines.push(`👥 Group Size: ${group.members.length} members (Avg: ${formatCurrency(avg, group.currency)}/person)`);
    lines.push(`🧾 Total Expenses Logged: ${group.expenses.length}`);
    lines.push(``);
    lines.push(`📋 MEMBER BALANCES:`);
    balances.forEach((b) => {
      const net = b.netBalance;
      const status = net > 0 ? '🟢 RECEIVES' : net < 0 ? '🔴 OWES' : '⚪ SETTLED';
      lines.push(
        `• ${b.memberName}: Paid ${formatCurrency(b.totalPaid, group.currency)} | Consumed ${formatCurrency(b.totalShare, group.currency)} ➔ ${status}: ${formatCurrency(Math.abs(net), group.currency)}`
      );
    });
    lines.push(``);
    lines.push(`⚡ OPTIMIZED SETTLEMENT PLAN (EACH PERSON SENDS AT MOST 1 PAYMENT):`);
    if (settlements.length === 0) {
      lines.push(`🎉 Everyone is fully settled! Nothing left to settle.`);
    } else {
      settlements.forEach((tx, idx) => {
        const fromMem = group.members.find((m) => m.id === tx.fromMemberId);
        const toMem = group.members.find((m) => m.id === tx.toMemberId);
        const status = tx.isPaid ? ' [PAID ✅]' : ' [PENDING]';
        const paymentInfo = toMem?.paymentDetails ? ` (${toMem.paymentDetails})` : '';
        lines.push(
          `${idx + 1}. ${fromMem?.name} ➔ ${toMem?.name}: ${formatCurrency(tx.amount, group.currency)}${paymentInfo}${status}`
        );
      });
    }
    lines.push(`─────────────────────────────────────────`);
    lines.push(`Generated by SplitWisePro 🚀`);
  }

  return lines.join('\n');
}

/**
 * Generates personal detailed text report for a single member.
 */
export function generateMemberReportText(
  group: Group,
  memberId: string,
  balances: MemberBalance[],
  settlements: SettlementTransaction[],
  lang: Language = 'en'
): string {
  const isVi = lang === 'vi';
  const member = group.members.find((m) => m.id === memberId);
  const balance = balances.find((b) => b.memberId === memberId);
  if (!member || !balance) return '';

  const lines: string[] = [];

  // 1. Expenses paid
  const paidExpenses = group.expenses.filter((e) => {
    if (e.isMultiplePayers && e.multiplePayers) {
      return e.multiplePayers.some((p) => p.memberId === memberId && p.amount > 0);
    }
    return e.payerId === memberId;
  });

  // 2. Expenses consumed
  const consumedExpenses = group.expenses.filter((e) =>
    e.beneficiaries.some((b) => b.memberId === memberId && b.amount > 0)
  );

  const outgoing = settlements.filter((tx) => tx.fromMemberId === memberId);
  const incoming = settlements.filter((tx) => tx.toMemberId === memberId);

  if (isVi) {
    lines.push(`🧾 BÁO CÁO CÁ NHÂN: ${member.name.toUpperCase()}`);
    lines.push(`Chuyến đi: ${group.name}`);
    lines.push(`─────────────────────────────────────────`);
    lines.push(`💵 CÁC KHOẢN BẠN ĐÃ CHI TRẢ (Tổng: ${formatCurrency(balance.totalPaid, group.currency)}):`);
    if (paidExpenses.length === 0) {
      lines.push(`  (Không có)`);
    } else {
      paidExpenses.forEach((e) => {
        let paidAmt = e.amount;
        if (e.isMultiplePayers && e.multiplePayers) {
          paidAmt = e.multiplePayers.find((p) => p.memberId === memberId)?.amount || 0;
        }
        lines.push(`  + ${e.description}: ${formatCurrency(paidAmt, group.currency)} (Tổng bill ${formatCurrency(e.amount, group.currency)})`);
      });
    }
    lines.push(``);
    lines.push(`🍽️ CÁC KHOẢN BẠN THAM GIA THỤ HƯỞNG (Tổng: ${formatCurrency(balance.totalShare, group.currency)}):`);
    if (consumedExpenses.length === 0) {
      lines.push(`  (Không có)`);
    } else {
      consumedExpenses.forEach((e) => {
        const share = e.beneficiaries.find((b) => b.memberId === memberId)?.amount || 0;
        lines.push(`  - ${e.description}: ${formatCurrency(share, group.currency)} (Chia cho ${e.selectedMemberIds.length} người)`);
      });
    }
    lines.push(``);
    lines.push(`⚖️ KẾT QUẢ SỐ DƯ RÒNG:`);
    if (balance.netBalance > 0.01) {
      lines.push(`🟢 BẠN ĐƯỢC NHẬN LẠI: +${formatCurrency(balance.netBalance, group.currency)}`);
      incoming.forEach((tx) => {
        const fromM = group.members.find((m) => m.id === tx.fromMemberId);
        lines.push(`  • ${fromM?.name} chuyển cho bạn: ${formatCurrency(tx.amount, group.currency)} ${tx.isPaid ? '(Đã nhận ✅)' : '(Chờ chuyển)'}`);
      });
    } else if (balance.netBalance < -0.01) {
      lines.push(`🔴 BẠN CẦN THANH TOÁN: -${formatCurrency(Math.abs(balance.netBalance), group.currency)}`);
      lines.push(`  🎯 LỘ TRÌNH THANH TOÁN (Chỉ chuyển đúng 1 lần):`);
      outgoing.forEach((tx) => {
        const toM = group.members.find((m) => m.id === tx.toMemberId);
        const payInfo = toM?.paymentDetails ? `\n    STK/Thông tin: ${toM.paymentDetails}` : '';
        lines.push(`  ➔ Chuyển cho ${toM?.name}: ${formatCurrency(tx.amount, group.currency)}${payInfo}`);
      });
    } else {
      lines.push(`⚪ BẠN ĐÃ HUỀ VỐN (Số dư $0)`);
    }
    lines.push(`─────────────────────────────────────────`);
  } else {
    lines.push(`🧾 PERSONAL EXPENSE REPORT: ${member.name.toUpperCase()}`);
    lines.push(`Group: ${group.name}`);
    lines.push(`─────────────────────────────────────────`);
    lines.push(`💵 EXPENSES YOU PAID FOR (Total: ${formatCurrency(balance.totalPaid, group.currency)}):`);
    if (paidExpenses.length === 0) {
      lines.push(`  (None)`);
    } else {
      paidExpenses.forEach((e) => {
        let paidAmt = e.amount;
        if (e.isMultiplePayers && e.multiplePayers) {
          paidAmt = e.multiplePayers.find((p) => p.memberId === memberId)?.amount || 0;
        }
        lines.push(`  + ${e.description}: ${formatCurrency(paidAmt, group.currency)} (Total bill ${formatCurrency(e.amount, group.currency)})`);
      });
    }
    lines.push(``);
    lines.push(`🍽️ EXPENSES YOU PARTICIPATED IN (Total: ${formatCurrency(balance.totalShare, group.currency)}):`);
    if (consumedExpenses.length === 0) {
      lines.push(`  (None)`);
    } else {
      consumedExpenses.forEach((e) => {
        const share = e.beneficiaries.find((b) => b.memberId === memberId)?.amount || 0;
        lines.push(`  - ${e.description}: ${formatCurrency(share, group.currency)} (Split with ${e.selectedMemberIds.length} members)`);
      });
    }
    lines.push(``);
    lines.push(`⚖️ FINAL NET BALANCE:`);
    if (balance.netBalance > 0.01) {
      lines.push(`🟢 YOU RECEIVE: +${formatCurrency(balance.netBalance, group.currency)}`);
      incoming.forEach((tx) => {
        const fromM = group.members.find((m) => m.id === tx.fromMemberId);
        lines.push(`  • ${fromM?.name}: ${formatCurrency(tx.amount, group.currency)} ${tx.isPaid ? '(Received ✅)' : '(Pending)'}`);
      });
    } else if (balance.netBalance < -0.01) {
      lines.push(`🔴 TO PAY: -${formatCurrency(Math.abs(balance.netBalance), group.currency)}`);
      lines.push(`  🎯 YOUR SINGLE-TRANSFER PAYMENT:`);
      outgoing.forEach((tx) => {
        const toM = group.members.find((m) => m.id === tx.toMemberId);
        const payInfo = toM?.paymentDetails ? `\n    Payment info: ${toM.paymentDetails}` : '';
        lines.push(`  ➔ Pay ${toM?.name}: ${formatCurrency(tx.amount, group.currency)}${payInfo}`);
      });
    } else {
      lines.push(`⚪ YOU ARE FULLY SETTLED (Net balance: $0)`);
    }
    lines.push(`─────────────────────────────────────────`);
  }

  return lines.join('\n');
}

/**
 * Downloads a CSV spreadsheet of all expenses and the settlement matrix.
 */
export function downloadExpensesCSV(group: Group, balances: MemberBalance[], lang: Language = 'en'): void {
  const isVi = lang === 'vi';
  const rows: string[][] = [];

  rows.push([isVi ? 'DANH SÁCH CHI TIÊU' : 'EXPENSE BREAKDOWN', group.name]);
  rows.push([
    isVi ? 'Ngày' : 'Date',
    isVi ? 'Tên khoản chi' : 'Description',
    isVi ? 'Tổng tiền' : 'Total Amount',
    isVi ? 'Người thanh toán' : 'Paid By',
    isVi ? 'Người cùng chia' : 'Split With (Subgroup / All)',
    isVi ? 'Ghi chú' : 'Notes',
  ]);

  group.expenses.forEach((e) => {
    let payerName = '';
    if (e.isMultiplePayers && e.multiplePayers) {
      payerName = e.multiplePayers
        .map((p) => {
          const m = group.members.find((mem) => mem.id === p.memberId);
          return `${m?.name || '?'}: ${p.amount}`;
        })
        .join('; ');
    } else {
      const payer = group.members.find((m) => m.id === e.payerId);
      payerName = payer?.name || (isVi ? 'Không rõ' : 'Unknown');
    }

    const participants = e.selectedMemberIds
      .map((id) => group.members.find((m) => m.id === id)?.name || '?')
      .join(', ');

    rows.push([
      e.date,
      `"${e.description}"`,
      e.amount.toString(),
      `"${payerName}"`,
      `"${participants}"`,
      `"${e.note || ''}"`,
    ]);
  });

  rows.push([]);
  rows.push([isVi ? 'BẢNG CÂN ĐỐI SỐ DƯ' : 'FINAL NET BALANCES']);
  rows.push([
    isVi ? 'Thành viên' : 'Member',
    isVi ? 'Tổng đã chi' : 'Total Paid',
    isVi ? 'Tổng tiêu thụ' : 'Total Share Consumed',
    isVi ? 'Số dư ròng (+ Nhận / - Nợ)' : 'Net Balance (+ Receive / - Owe)',
  ]);

  balances.forEach((b) => {
    rows.push([
      b.memberName,
      b.totalPaid.toString(),
      b.totalShare.toString(),
      b.netBalance.toString(),
    ]);
  });

  const csvContent = '\uFEFF' + rows.map((r) => r.join(',')).join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${group.name.replace(/\s+/g, '_')}_expenses.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
